package cn.com.softvan.dao.daointer.regions;

import cn.com.softvan.dao.entity.regions.TcAdiVillage;

public interface ITcAdiVillageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_village
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int deleteByPrimaryKey(String villageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_village
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int insert(TcAdiVillage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_village
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int insertSelective(TcAdiVillage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_village
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    TcAdiVillage selectByPrimaryKey(String villageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_village
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int updateByPrimaryKeySelective(TcAdiVillage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_village
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int updateByPrimaryKey(TcAdiVillage record);
}