package cn.com.softvan.dao.daointer.regions;

import cn.com.softvan.dao.entity.regions.TcAdiProvince;

public interface ITcAdiProvinceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_province
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int deleteByPrimaryKey(String provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_province
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int insert(TcAdiProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_province
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int insertSelective(TcAdiProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_province
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    TcAdiProvince selectByPrimaryKey(String provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_province
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int updateByPrimaryKeySelective(TcAdiProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_province
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int updateByPrimaryKey(TcAdiProvince record);
}