package cn.com.softvan.dao.daointer.regions;

import cn.com.softvan.dao.entity.regions.TcAdiTown;

public interface ITcAdiTownDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_town
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int deleteByPrimaryKey(String townId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_town
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int insert(TcAdiTown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_town
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int insertSelective(TcAdiTown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_town
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    TcAdiTown selectByPrimaryKey(String townId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_town
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int updateByPrimaryKeySelective(TcAdiTown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_town
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int updateByPrimaryKey(TcAdiTown record);
}