package cn.com.softvan.dao.daointer.regions;

import java.util.List;

import cn.com.softvan.dao.entity.regions.TcAdiCounty;

public interface ITcAdiCountyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_county
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int deleteByPrimaryKey(String countyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_county
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int insert(TcAdiCounty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_county
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int insertSelective(TcAdiCounty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_county
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    TcAdiCounty selectByPrimaryKey(String countyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_county
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int updateByPrimaryKeySelective(TcAdiCounty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_county
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int updateByPrimaryKey(TcAdiCounty record);
    
    public List<TcAdiCounty> fuzzySearchCounty(String countyId);
}