package cn.com.softvan.dao.daointer.regions;

import cn.com.softvan.dao.entity.regions.TcAdiCity;

public interface ITcAdiCityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_city
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int deleteByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_city
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int insert(TcAdiCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_city
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int insertSelective(TcAdiCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_city
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    TcAdiCity selectByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_city
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int updateByPrimaryKeySelective(TcAdiCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_adi_city
     *
     * @mbggenerated Tue Feb 25 17:16:36 CST 2014
     */
    int updateByPrimaryKey(TcAdiCity record);
}