package cn.com.softvan.dao.daointer.sys;

import cn.com.softvan.dao.entity.sys.TcSysEmail;

public interface ITcSysEmailDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_email_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int deleteByPrimaryKey(String mailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_email_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int insert(TcSysEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_email_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int insertSelective(TcSysEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_email_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    TcSysEmail selectByPrimaryKey(String mailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_email_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int updateByPrimaryKeySelective(TcSysEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_email_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int updateByPrimaryKeyWithBLOBs(TcSysEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_email_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int updateByPrimaryKey(TcSysEmail record);
}