package cn.com.softvan.dao.daointer.sys;

import cn.com.softvan.dao.entity.sys.TcSysSms;

public interface ITcSysSmsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_sms_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int deleteByPrimaryKey(String smsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_sms_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int insert(TcSysSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_sms_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int insertSelective(TcSysSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_sms_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    TcSysSms selectByPrimaryKey(String smsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_sms_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int updateByPrimaryKeySelective(TcSysSms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_sms_info
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int updateByPrimaryKey(TcSysSms record);
}