/*
 * 接口Dao类  系统变量设置
 *
 * VERSION  DATE        BY              REASON
 * -------- ----------- --------------- ------------------------------------------
 * 1.00     2014.02.26  wangzi           程序发布
 * -------- ----------- --------------- ------------------------------------------
 * Copyright 2014 车主管家  System. - All Rights Reserved.
 *
 */
package cn.com.softvan.dao.daointer.sys;

import cn.com.softvan.dao.entity.sys.TcSysVariable;
/**
 * <p> 系统变量设置 <p>
 * @author wangzi
 *
 */
public interface ITcSysVariableDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_system_variable
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int deleteByPrimaryKey(TcSysVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_system_variable
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int insert(TcSysVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_system_variable
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int insertSelective(TcSysVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_system_variable
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    TcSysVariable selectByPrimaryKey(TcSysVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_system_variable
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int updateByPrimaryKeySelective(TcSysVariable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_system_variable
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int updateByPrimaryKey(TcSysVariable record);
}