package cn.com.softvan.dao.daointer.user;

import cn.com.softvan.dao.entity.user.TcUaUmBaseUser;

public interface ITcUaUmBaseUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_base_user
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_base_user
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int insert(TcUaUmBaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_base_user
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int insertSelective(TcUaUmBaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_base_user
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    TcUaUmBaseUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_base_user
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int updateByPrimaryKeySelective(TcUaUmBaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_base_user
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int updateByPrimaryKey(TcUaUmBaseUser record);
}