/*
 * 接口Dao类   权限
 *
 * VERSION  DATE        BY              REASON
 * -------- ----------- --------------- ------------------------------------------
 * 1.00     2014.02.26  wuxiaogang           程序.发布
 * -------- ----------- --------------- ------------------------------------------
 * Copyright 2014 童励  System. - All Rights Reserved.
 *
 */
package cn.com.softvan.dao.daointer.user;

import cn.com.softvan.dao.entity.user.TcUaUmPermission;
/**
 * <p> 权限 <p>
 * @author wuxiaogang
 *
 */
public interface ITcUaUmPermissionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_permission
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int deleteByPrimaryKey(TcUaUmPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_permission
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int insert(TcUaUmPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_permission
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int insertSelective(TcUaUmPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_permission
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    TcUaUmPermission selectByPrimaryKey(TcUaUmPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_permission
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int updateByPrimaryKeySelective(TcUaUmPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_permission
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int updateByPrimaryKey(TcUaUmPermission record);
}