package cn.com.softvan.dao.daointer.user;

import cn.com.softvan.dao.entity.user.TcUaUmOperationLog;

public interface ITcUaUmOperationLogDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_operation_log
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_operation_log
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int insert(TcUaUmOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_operation_log
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int insertSelective(TcUaUmOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_operation_log
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    TcUaUmOperationLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_operation_log
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int updateByPrimaryKeySelective(TcUaUmOperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_operation_log
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int updateByPrimaryKey(TcUaUmOperationLog record);
}