package cn.com.softvan.dao.daointer.user;

import cn.com.softvan.dao.entity.user.TcUaUmBaseRole;

public interface ITcUaUmBaseRoleDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_base_role
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_base_role
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int insert(TcUaUmBaseRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_base_role
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int insertSelective(TcUaUmBaseRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_base_role
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    TcUaUmBaseRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_base_role
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int updateByPrimaryKeySelective(TcUaUmBaseRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_base_role
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int updateByPrimaryKey(TcUaUmBaseRole record);
}