package cn.com.softvan.dao.daointer.user;

import cn.com.softvan.dao.entity.user.TcUaUmPermissionGroup;

public interface ITcUaUmPermissionGroupDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_permission_group
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_permission_group
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int insert(TcUaUmPermissionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_permission_group
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int insertSelective(TcUaUmPermissionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_permission_group
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    TcUaUmPermissionGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_permission_group
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int updateByPrimaryKeySelective(TcUaUmPermissionGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ua_um_permission_group
     *
     * @mbggenerated Tue Feb 25 17:19:04 CST 2014
     */
    int updateByPrimaryKey(TcUaUmPermissionGroup record);
}