/*
 * 接口Dao类   车主管家附件关联 Dao类
 *
 * VERSION  DATE        BY              REASON
 * -------- ----------- --------------- ------------------------------------------
 * 1.00     2014.02.26  wuxiaogang           程序.发布
 * -------- ----------- --------------- ------------------------------------------
 * Copyright 2014 车主管家  System. - All Rights Reserved.
 *
 */
package cn.com.softvan.dao.daointer;

import java.util.List;

import cn.com.softvan.dao.entity.TcFileLink;
/**
 * <p> 车主管家附件关联 Dao类 <p>
 * @author wuxiaogang
 *
 */
public interface ITcFileLinkDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file_link
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int deleteByPrimaryKey(TcFileLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file_link
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int insert(TcFileLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file_link
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int insertSelective(TcFileLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file_link
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    List<TcFileLink> selectByPrimaryKey(TcFileLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file_link
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int updateByPrimaryKeySelective(TcFileLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file_link
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int updateByPrimaryKey(TcFileLink record);
    
    
    List<TcFileLink> getLinkList(TcFileLink link);
    
}