package cn.com.softvan.dao.daointer;

import java.util.List;

import cn.com.softvan.dao.entity.TcFile;

public interface ITcFileDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int deleteByPrimaryKey(String fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int insert(TcFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int insertSelective(TcFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    TcFile selectByPrimaryKey(String fileId);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    TcFile selectByPrimaryKey(TcFile record);
    
    /**
     * 通过(报案 ...)主键 查找附件信息
     * 
     * @param linkId 
     * @return
     */
    List<TcFile> selectByLinkId(String linkId);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int updateByPrimaryKeySelective(TcFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_ct_file
     *
     * @mbggenerated Tue Feb 25 17:17:41 CST 2014
     */
    int updateByPrimaryKey(TcFile record);
    
    
    
}